heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running a Minecraft
  server.  The Minecraft server will be setup leveraging Chef solo.

parameter_groups:

- label: Server Settings
  parameters:
  - server_hostname
  - image
  - flavor

- label: Minecraft Settings
  parameters:
  - minecraft_server_port
  - minecraft_gamemode
  - minecraft_spawn_animals
  - minecraft_spawn_npcs
  - minecraft_spawn_monsters

parameters:

  server_hostname:
    label: Server Name
    description: Hostname to use for setting the server name.
    type: string
    default: minecraft
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Server Image
    description: Operating system to use for the Minecraft Server
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 14.04 LTS (Trusty Tahr)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Cloud Server flavor
    description: Flavor of Cloud server to use
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  minecraft_server_port:
    label: Minecraft Server Port
    description: Port to run Minecraft server on
    type: number
    default: 25565
    constraints:
    - range:
        min: 1024
        max: 65535
      description: |
        Port must be an unprivileged port in the range of 1024-65535

  minecraft_gamemode:
    label: Game Mode
    description: Mode of gameplay
    type: number
    default: 0
    constraints:
    - range:
        min: 0
        max: 3
      description: |
        0: Survival, 1: Creative, 2: Adventure, 3: Spectator

  minecraft_spawn_animals:
    label: Spawn Animals
    description: Spawn animals
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  minecraft_spawn_npcs:
    label: Spawn Villagers
    description: Spawn villagers
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  minecraft_spawn_monsters:
    label: Spawn Monsters
    description: Spawn monsters
    type: string
    default: "true"
    constraints:
    - allowed_values:
      - "true"
      - "false"

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/minecraft

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.2

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  minecraft_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }

  minecraft_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: minecraft_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [minecraft_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        minecraft:
          url: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.9/minecraft_server.1.7.9.jar
          checksum: f7b9150d05c2cf8c48541527de310557e6bd9bde73e8ac9479e8ffe722c60a21
          properties:
            server-port: { get_param: minecraft_server_port }
            query.port: { get_param: minecraft_server_port }
            rcon.port: 25575
            gamemode: { get_param: minecraft_gamemode }
            spawn-animals: { get_param: minecraft_spawn_animals }
            spawn-npcs: { get_param: minecraft_spawn_npcs }
            spawn-monsters: { get_param: minecraft_spawn_monsters }
        rax:
          firewall:
            tcp: [ { get_param: minecraft_server_port } ]
        run_list: ["recipe[apt]",
                   "recipe[minecraft]",
                   "recipe[rax-firewall]"]


outputs:
  private_key:
    description: Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [minecraft_server, accessIPv4] }

  server_port:
    description: Minecraft Port
    value: { get_param: minecraft_server_port }
